name: Convert UTC to JST
description: |
    入力がない場合は現在の時刻を使用し、入力がある場合はタイムスタンプを受け取ってJSTに変換します。
inputs:
    timestamp:
        description: UTCタイムスタンプ
        required: false
        default: ""
outputs:
    jst_time:
        description: JST形式の時刻
        value: ${{ steps.convert.outputs.jst_time }}
runs:
    using: "composite"
    steps:
        - id: convert
          run: |
              NINE_HOURS_IN_SECONDS=32400
              if [ -z "${{ inputs.timestamp }}" ]; then
                timestamp=$(date +%s)
              else
                timestamp=${{ inputs.timestamp }}
              fi
              jst_timestamp=$(echo "$timestamp + $NINE_HOURS_IN_SECONDS" | bc)
              jst_time=$(date -d "@$jst_timestamp" +"%a %m %d %H:%M:%S JST %Y")
              echo "jst_time=${jst_time}" >> $GITHUB_OUTPUT
          shell: bash
