name: Concurrency
on: push
concurrency: ${{ github.workflow }} # concurrency manage booting multiple workflow
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 120
