name: Conditions workflow
on: push
jobs:
    skip-or-run:
        if: ${{ github.actor == 'aloekun'}}
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Hello'
    fail:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
            - run: echo "Failure World"
              if: ${{ failure() }}
